name: chewie
description: A video player for Flutter with Cupertino and Material play controls
version: 0.9.8+2
homepage: https://github.com/brianegan/chewie
authors:
  - Brian Egan <brian@brianegan.com>
  - Ben Hagen <ben@ottomatic.io>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  open_iconic_flutter: ">=0.3.0 <0.4.0"
  video_player: ">=0.7.0 <0.11.0"
  wakelock: ">=0.1.2 <0.2.0"
  screen:
    git:
      url: https://github.com/hwh97/flutter_screen.git
  sys_volume:
    git:
      url: https://github.com/hwh97/flutter_volume.git
  event_bus:
#    path: /Users/jiajunzhou/Documents/i2_school_packages__git/event_bus
    git:
      url: https://github.com/jun7572/event_bus.git

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
